### ISSUE TITLE
Update endorsement headshot

### ISSUE THREAD

**Issue by epicfaace** [ashwinforga/ashwinforgeorgia.com#37]
![IMG_9008](https://github.com/ashwinforga/ashwinforgeorgia.com/assets/1689183/eed87ab4-ca04-4f5d-beda-f8c95c403e49)

**Comment by epicfaace** [comment]
@OlliMulchandani can you help with this? Make sure you crop the image so it's the same dimensions as the other headshots.

**Comment by OlliMulchandani** [comment]
Is this Kannan Udayarajan? @epicfaace

**Comment by epicfaace** [comment]
Yes
