### ISSUE TITLE
Press - RNS

### ISSUE THREAD

**Issue by epicfaace** [ashwinforga/ashwinforgeorgia.com#38]
https://religionnews.com/2024/06/06/this-gen-z-politician-wants-to-talk-about-religion-more-not-less/

**Comment by epicfaace** [comment]
@OlliMulchandani please add

**Comment by OlliMulchandani** [comment]
Any specific quote for this one? I'll use this one for now: "Seva, the Hindu concept of service, helped inspire him to run for office, and he thinks faith has much to add to politics, which he thinks of as a way to change hearts and minds. Religion should not be overlooked as a means to achieve that, he said, pointing to Martin Luther King Jr. and Mahatma Gandhi as role models. " @epicfaace

**Comment by epicfaace** [comment]
No can you pick one? We can change later too


--
Ashwin Ramaswami
